'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18034
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''
<Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1), _
 Global.System.Security.Permissions.PermissionSetAttribute(Global.System.Security.Permissions.SecurityAction.Demand, Name:="FullTrust")> _
Partial Public NotInheritable Class Sheet1
    Inherits Microsoft.Office.Tools.Excel.WorksheetBase

    Friend WithEvents DateCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents TypeCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents SymbolCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents QtyCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents PriceCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents TotalTCostCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents TotalTValueCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents InterestSLTCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents TeamIDCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents TransactionQueueLst As Microsoft.Office.Tools.Excel.ListObject

    Friend WithEvents CurrentDateCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents TransactionDateCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents cAcctATCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents cAcctCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents MarginsCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents _30MarginsCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents MaxMarginsCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents TPV_at_StartCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents TaTPVCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents TE__weightedCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents TECell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents TPVCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents Margin_ATCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents Chart_1 As Microsoft.Office.Tools.Excel.Chart

    Friend WithEvents SecondsLeftCell1 As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents SecondsLeftCell As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents UnderlierRange As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents VolatilityRange As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents PortfolioDeltaRange As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents RecommendationRange As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents SymbolRange As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents QtyRange As Microsoft.Office.Tools.Excel.NamedRange

    Friend WithEvents StockTTypeCBox As Microsoft.Office.Tools.Excel.Controls.ComboBox

    Friend WithEvents TickerCBox As Microsoft.Office.Tools.Excel.Controls.ComboBox

    Friend WithEvents StockQtyTBox As Microsoft.Office.Tools.Excel.Controls.TextBox

    Friend WithEvents StockTradePreviewBtn As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents StockTradeBtn As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents OptionTTypeCBox As Microsoft.Office.Tools.Excel.Controls.ComboBox

    Friend WithEvents SymbolCBox As Microsoft.Office.Tools.Excel.Controls.ComboBox

    Friend WithEvents OptionQtyTBox As Microsoft.Office.Tools.Excel.Controls.TextBox

    Friend WithEvents OptionTradePreviewBtn As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents OptionTradeBtn As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents TradeItBtn As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents Button1 As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents Button2 As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents Button3 As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents Button4 As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents Button5 As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents Button6 As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents Button7 As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents Button8 As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents Button9 As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents Button10 As Microsoft.Office.Tools.Excel.Controls.Button

    Friend WithEvents Button11 As Microsoft.Office.Tools.Excel.Controls.Button

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Public Sub New(ByVal factory As Global.Microsoft.Office.Tools.Excel.Factory, ByVal serviceProvider As Global.System.IServiceProvider)
        MyBase.New(factory, serviceProvider, "Sheet1", "Sheet1")
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Protected Overrides Sub Initialize()
        MyBase.Initialize()
        Globals.Sheet1 = Me
        Global.System.Windows.Forms.Application.EnableVisualStyles()
        Me.InitializeCachedData()
        Me.InitializeControls()
        Me.InitializeComponents()
        Me.InitializeData()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Protected Overrides Sub FinishInitialization()
        Me.OnStartup()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Protected Overrides Sub InitializeDataBindings()
        Me.BeginInitialization()
        Me.BindToData()
        Me.EndInitialization()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeCachedData()
        If (Me.DataHost Is Nothing) Then
            Return
        End If
        If Me.DataHost.IsCacheInitialized Then
            Me.DataHost.FillCachedData(Me)
        End If
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeData()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub BindToData()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Sub StartCaching(ByVal MemberName As String)
        Me.DataHost.StartCaching(Me, MemberName)
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Sub StopCaching(ByVal MemberName As String)
        Me.DataHost.StopCaching(Me, MemberName)
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Function IsCached(ByVal MemberName As String) As Boolean
        Return Me.DataHost.IsCached(Me, MemberName)
    End Function

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub BeginInitialization()
        Me.BeginInit()
        Me.DateCell.BeginInit()
        Me.TypeCell.BeginInit()
        Me.SymbolCell.BeginInit()
        Me.QtyCell.BeginInit()
        Me.PriceCell.BeginInit()
        Me.TotalTCostCell.BeginInit()
        Me.TotalTValueCell.BeginInit()
        Me.InterestSLTCell.BeginInit()
        Me.TeamIDCell.BeginInit()
        Me.TransactionQueueLst.BeginInit()
        Me.CurrentDateCell.BeginInit()
        Me.TransactionDateCell.BeginInit()
        Me.cAcctATCell.BeginInit()
        Me.cAcctCell.BeginInit()
        Me.MarginsCell.BeginInit()
        Me._30MarginsCell.BeginInit()
        Me.MaxMarginsCell.BeginInit()
        Me.TPV_at_StartCell.BeginInit()
        Me.TaTPVCell.BeginInit()
        Me.TE__weightedCell.BeginInit()
        Me.TECell.BeginInit()
        Me.TPVCell.BeginInit()
        Me.Margin_ATCell.BeginInit()
        Me.Chart_1.BeginInit()
        Me.SecondsLeftCell1.BeginInit()
        Me.SecondsLeftCell.BeginInit()
        Me.UnderlierRange.BeginInit()
        Me.VolatilityRange.BeginInit()
        Me.PortfolioDeltaRange.BeginInit()
        Me.RecommendationRange.BeginInit()
        Me.SymbolRange.BeginInit()
        Me.QtyRange.BeginInit()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub EndInitialization()
        Me.QtyRange.EndInit()
        Me.SymbolRange.EndInit()
        Me.RecommendationRange.EndInit()
        Me.PortfolioDeltaRange.EndInit()
        Me.VolatilityRange.EndInit()
        Me.UnderlierRange.EndInit()
        Me.SecondsLeftCell.EndInit()
        Me.SecondsLeftCell1.EndInit()
        Me.Chart_1.EndInit()
        Me.Margin_ATCell.EndInit()
        Me.TPVCell.EndInit()
        Me.TECell.EndInit()
        Me.TE__weightedCell.EndInit()
        Me.TaTPVCell.EndInit()
        Me.TPV_at_StartCell.EndInit()
        Me.MaxMarginsCell.EndInit()
        Me._30MarginsCell.EndInit()
        Me.MarginsCell.EndInit()
        Me.cAcctCell.EndInit()
        Me.cAcctATCell.EndInit()
        Me.TransactionDateCell.EndInit()
        Me.CurrentDateCell.EndInit()
        Me.TransactionQueueLst.EndInit()
        Me.TeamIDCell.EndInit()
        Me.InterestSLTCell.EndInit()
        Me.TotalTValueCell.EndInit()
        Me.TotalTCostCell.EndInit()
        Me.PriceCell.EndInit()
        Me.QtyCell.EndInit()
        Me.SymbolCell.EndInit()
        Me.TypeCell.EndInit()
        Me.DateCell.EndInit()
        Me.EndInit()
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeControls()
        Me.DateCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "DateCell", "DateCell", Me)
        Me.TypeCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TypeCell", "TypeCell", Me)
        Me.SymbolCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "SymbolCell", "SymbolCell", Me)
        Me.QtyCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "QtyCell", "QtyCell", Me)
        Me.PriceCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "PriceCell", "PriceCell", Me)
        Me.TotalTCostCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TotalTCostCell", "TotalTCostCell", Me)
        Me.TotalTValueCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TotalTValueCell", "TotalTValueCell", Me)
        Me.InterestSLTCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "InterestSLTCell", "InterestSLTCell", Me)
        Me.TeamIDCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TeamIDCell", "TeamIDCell", Me)
        Me.TransactionQueueLst = Globals.Factory.CreateListObject(Nothing, Nothing, "Sheet1:TransactionQueueLst", "TransactionQueueLst", Me)
        Me.CurrentDateCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CurrentDateCell", "CurrentDateCell", Me)
        Me.TransactionDateCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TransactionDateCell", "TransactionDateCell", Me)
        Me.cAcctATCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "cAcctATCell", "cAcctATCell", Me)
        Me.cAcctCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "cAcctCell", "cAcctCell", Me)
        Me.MarginsCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "MarginsCell", "MarginsCell", Me)
        Me._30MarginsCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "_30MarginsCell", "_30MarginsCell", Me)
        Me.MaxMarginsCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "MaxMarginsCell", "MaxMarginsCell", Me)
        Me.TPV_at_StartCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TPV_at_StartCell", "TPV_at_StartCell", Me)
        Me.TaTPVCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TaTPVCell", "TaTPVCell", Me)
        Me.TE__weightedCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TE__weightedCell", "TE__weightedCell", Me)
        Me.TECell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TECell", "TECell", Me)
        Me.TPVCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TPVCell", "TPVCell", Me)
        Me.Margin_ATCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Margin_ATCell", "Margin_ATCell", Me)
        Me.Chart_1 = Globals.Factory.CreateChart(Nothing, Nothing, "Sheet1:Chart 1", "Chart_1", Me)
        Me.SecondsLeftCell1 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "SecondsLeftCell1", "SecondsLeftCell1", Me)
        Me.SecondsLeftCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "SecondsLeftCell", "SecondsLeftCell", Me)
        Me.UnderlierRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "UnderlierRange", "UnderlierRange", Me)
        Me.VolatilityRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "VolatilityRange", "VolatilityRange", Me)
        Me.PortfolioDeltaRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "PortfolioDeltaRange", "PortfolioDeltaRange", Me)
        Me.RecommendationRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RecommendationRange", "RecommendationRange", Me)
        Me.SymbolRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "SymbolRange", "SymbolRange", Me)
        Me.QtyRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "QtyRange", "QtyRange", Me)
        Me.StockTTypeCBox = New Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "10BE659191327D1409F1BB111F606F9C6528F1", "10BE659191327D1409F1BB111F606F9C6528F1", Me, "StockTTypeCBox")
        Me.TickerCBox = New Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "2CA9D812826A4C24CAF291A22CA6D6E946F6D2", "2CA9D812826A4C24CAF291A22CA6D6E946F6D2", Me, "TickerCBox")
        Me.StockQtyTBox = New Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "3B06E73A13F6893456839EFE3030D9FD9258A3", "3B06E73A13F6893456839EFE3030D9FD9258A3", Me, "StockQtyTBox")
        Me.StockTradePreviewBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "4690CD83749025447CC49ECC42658EE4C659B4", "4690CD83749025447CC49ECC42658EE4C659B4", Me, "StockTradePreviewBtn")
        Me.StockTradeBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "56009AD755F7755471E587CA5FE749B1CC9AF5", "56009AD755F7755471E587CA5FE749B1CC9AF5", Me, "StockTradeBtn")
        Me.OptionTTypeCBox = New Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "68B745CC06AD8564D47686ED6C50A248329C06", "68B745CC06AD8564D47686ED6C50A248329C06", Me, "OptionTTypeCBox")
        Me.SymbolCBox = New Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "7080376B57360E74C6B79EEE7178F8196C5697", "7080376B57360E74C6B79EEE7178F8196C5697", Me, "SymbolCBox")
        Me.OptionQtyTBox = New Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "87040C98D836C384C468A36683BCA488E62D78", "87040C98D836C384C468A36683BCA488E62D78", Me, "OptionQtyTBox")
        Me.OptionTradePreviewBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "9C1A3DB4691E4D942D19AB8795E79AE723BEC9", "9C1A3DB4691E4D942D19AB8795E79AE723BEC9", Me, "OptionTradePreviewBtn")
        Me.OptionTradeBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "132E810CC1EFAE1443D19E7910080B3343EE91", "132E810CC1EFAE1443D19E7910080B3343EE91", Me, "OptionTradeBtn")
        Me.TradeItBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "1CD452AFE16A05144FE18E1011EE33F1737EB1", "1CD452AFE16A05144FE18E1011EE33F1737EB1", Me, "TradeItBtn")
        Me.Button1 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "1B3FB9C8016C4E146E61B7341256ACD7D6F381", "1B3FB9C8016C4E146E61B7341256ACD7D6F381", Me, "Button1")
        Me.Button2 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "11DA5537D139C5145C7199321007912CCEE931", "11DA5537D139C5145C7199321007912CCEE931", Me, "Button2")
        Me.Button3 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "238929E5B24C53247582B6DC25D8C80D69E492", "238929E5B24C53247582B6DC25D8C80D69E492", Me, "Button3")
        Me.Button4 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "2BA45FB6420758240D32AC5F2D7004F037C482", "2BA45FB6420758240D32AC5F2D7004F037C482", Me, "Button4")
        Me.Button5 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "2260C26942B224246F02853A209317CA042832", "2260C26942B224246F02853A209317CA042832", Me, "Button5")
        Me.Button6 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "2536445BA2C8A32426A2B8EE20054718983692", "2536445BA2C8A32426A2B8EE20054718983692", Me, "Button6")
        Me.Button7 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "201B53E5621D2E24AFA2A78829F2B1A40E4FA2", "201B53E5621D2E24AFA2A78829F2B1A40E4FA2", Me, "Button7")
        Me.Button8 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "220D4983420598244EF2A92721C9D752E59092", "220D4983420598244EF2A92721C9D752E59092", Me, "Button8")
        Me.Button9 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "293DF9B8D2A1F624B042B97D2D4AE55418C5C2", "293DF9B8D2A1F624B042B97D2D4AE55418C5C2", Me, "Button9")
        Me.Button10 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "2C43D72F92D6F524FD3285D926A7B4C79917F2", "2C43D72F92D6F524FD3285D926A7B4C79917F2", Me, "Button10")
        Me.Button11 = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "20920EC8A278BC24A762A268287B0DEE94A6F2", "20920EC8A278BC24A762A268287B0DEE94A6F2", Me, "Button11")
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Private Sub InitializeComponents()
        '
        'StockTTypeCBox
        '
        Me.StockTTypeCBox.BackColor = System.Drawing.Color.FromArgb(CType(CType(192, Byte), Integer), CType(CType(192, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.StockTTypeCBox.Name = "StockTTypeCBox"
        Me.StockTTypeCBox.Text = "T. Type"
        '
        'TickerCBox
        '
        Me.TickerCBox.BackColor = System.Drawing.Color.FromArgb(CType(CType(192, Byte), Integer), CType(CType(192, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.TickerCBox.Name = "TickerCBox"
        Me.TickerCBox.Text = "Select"
        '
        'StockQtyTBox
        '
        Me.StockQtyTBox.BackColor = System.Drawing.Color.FromArgb(CType(CType(192, Byte), Integer), CType(CType(192, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.StockQtyTBox.Name = "StockQtyTBox"
        '
        'StockTradePreviewBtn
        '
        Me.StockTradePreviewBtn.BackColor = System.Drawing.Color.FromArgb(CType(CType(192, Byte), Integer), CType(CType(192, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.StockTradePreviewBtn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.StockTradePreviewBtn.Name = "StockTradePreviewBtn"
        Me.StockTradePreviewBtn.Text = "PREVIEW"
        Me.StockTradePreviewBtn.UseVisualStyleBackColor = False
        '
        'StockTradeBtn
        '
        Me.StockTradeBtn.BackColor = System.Drawing.Color.FromArgb(CType(CType(192, Byte), Integer), CType(CType(192, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.StockTradeBtn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.StockTradeBtn.Name = "StockTradeBtn"
        Me.StockTradeBtn.Text = "TRADE STOCK"
        Me.StockTradeBtn.UseVisualStyleBackColor = False
        '
        'OptionTTypeCBox
        '
        Me.OptionTTypeCBox.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.OptionTTypeCBox.Name = "OptionTTypeCBox"
        Me.OptionTTypeCBox.Text = "T. Type"
        '
        'SymbolCBox
        '
        Me.SymbolCBox.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.SymbolCBox.Name = "SymbolCBox"
        Me.SymbolCBox.Text = "Select"
        '
        'OptionQtyTBox
        '
        Me.OptionQtyTBox.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.OptionQtyTBox.Name = "OptionQtyTBox"
        '
        'OptionTradePreviewBtn
        '
        Me.OptionTradePreviewBtn.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.OptionTradePreviewBtn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.OptionTradePreviewBtn.Name = "OptionTradePreviewBtn"
        Me.OptionTradePreviewBtn.Text = "PREVIEW"
        Me.OptionTradePreviewBtn.UseVisualStyleBackColor = False
        '
        'OptionTradeBtn
        '
        Me.OptionTradeBtn.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.OptionTradeBtn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.OptionTradeBtn.Name = "OptionTradeBtn"
        Me.OptionTradeBtn.Text = "TRADE OPTION"
        Me.OptionTradeBtn.UseVisualStyleBackColor = False
        '
        'DateCell
        '
        Me.DateCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TypeCell
        '
        Me.TypeCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'SymbolCell
        '
        Me.SymbolCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'QtyCell
        '
        Me.QtyCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'PriceCell
        '
        Me.PriceCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TotalTCostCell
        '
        Me.TotalTCostCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TotalTValueCell
        '
        Me.TotalTValueCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'InterestSLTCell
        '
        Me.InterestSLTCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TeamIDCell
        '
        Me.TeamIDCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TransactionQueueLst
        '
        Me.TransactionQueueLst.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'CurrentDateCell
        '
        Me.CurrentDateCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TransactionDateCell
        '
        Me.TransactionDateCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'cAcctATCell
        '
        Me.cAcctATCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'cAcctCell
        '
        Me.cAcctCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'MarginsCell
        '
        Me.MarginsCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        '_30MarginsCell
        '
        Me._30MarginsCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'MaxMarginsCell
        '
        Me.MaxMarginsCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TPV_at_StartCell
        '
        Me.TPV_at_StartCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TaTPVCell
        '
        Me.TaTPVCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TE__weightedCell
        '
        Me.TE__weightedCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TECell
        '
        Me.TECell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TPVCell
        '
        Me.TPVCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'Margin_ATCell
        '
        Me.Margin_ATCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'Chart_1
        '
        Me.Chart_1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'SecondsLeftCell1
        '
        Me.SecondsLeftCell1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'SecondsLeftCell
        '
        Me.SecondsLeftCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TradeItBtn
        '
        Me.TradeItBtn.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.TradeItBtn.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.TradeItBtn.Font = New System.Drawing.Font("Arial", 6.75!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.TradeItBtn.ForeColor = System.Drawing.Color.Blue
        Me.TradeItBtn.Name = "TradeItBtn"
        Me.TradeItBtn.Text = "Trade It"
        Me.TradeItBtn.TextAlign = System.Drawing.ContentAlignment.TopCenter
        Me.TradeItBtn.UseVisualStyleBackColor = False
        '
        'Button1
        '
        Me.Button1.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.Button1.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Button1.Font = New System.Drawing.Font("Arial", 6.75!)
        Me.Button1.ForeColor = System.Drawing.Color.Blue
        Me.Button1.Name = "Button1"
        Me.Button1.Text = "Trade It"
        Me.Button1.TextAlign = System.Drawing.ContentAlignment.TopCenter
        Me.Button1.UseVisualStyleBackColor = False
        '
        'Button2
        '
        Me.Button2.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.Button2.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Button2.Font = New System.Drawing.Font("Arial", 6.75!)
        Me.Button2.ForeColor = System.Drawing.Color.Blue
        Me.Button2.Name = "Button2"
        Me.Button2.Text = "Trade It"
        Me.Button2.TextAlign = System.Drawing.ContentAlignment.TopCenter
        Me.Button2.UseVisualStyleBackColor = False
        '
        'Button3
        '
        Me.Button3.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.Button3.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Button3.Font = New System.Drawing.Font("Arial", 6.75!)
        Me.Button3.ForeColor = System.Drawing.Color.Blue
        Me.Button3.Name = "Button3"
        Me.Button3.Text = "Trade It"
        Me.Button3.TextAlign = System.Drawing.ContentAlignment.TopCenter
        Me.Button3.UseVisualStyleBackColor = False
        '
        'Button4
        '
        Me.Button4.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.Button4.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Button4.Font = New System.Drawing.Font("Arial", 6.75!)
        Me.Button4.ForeColor = System.Drawing.Color.Blue
        Me.Button4.Name = "Button4"
        Me.Button4.Text = "Trade It"
        Me.Button4.TextAlign = System.Drawing.ContentAlignment.TopCenter
        Me.Button4.UseVisualStyleBackColor = False
        '
        'Button5
        '
        Me.Button5.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.Button5.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Button5.Font = New System.Drawing.Font("Arial", 6.75!)
        Me.Button5.ForeColor = System.Drawing.Color.Blue
        Me.Button5.Name = "Button5"
        Me.Button5.Text = "Trade It"
        Me.Button5.TextAlign = System.Drawing.ContentAlignment.TopCenter
        Me.Button5.UseVisualStyleBackColor = False
        '
        'Button6
        '
        Me.Button6.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.Button6.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Button6.Font = New System.Drawing.Font("Arial", 6.75!)
        Me.Button6.ForeColor = System.Drawing.Color.Blue
        Me.Button6.Name = "Button6"
        Me.Button6.Text = "Trade It"
        Me.Button6.TextAlign = System.Drawing.ContentAlignment.TopCenter
        Me.Button6.UseVisualStyleBackColor = False
        '
        'Button7
        '
        Me.Button7.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.Button7.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Button7.Font = New System.Drawing.Font("Arial", 6.75!)
        Me.Button7.ForeColor = System.Drawing.Color.Blue
        Me.Button7.Name = "Button7"
        Me.Button7.Text = "Trade It"
        Me.Button7.TextAlign = System.Drawing.ContentAlignment.TopCenter
        Me.Button7.UseVisualStyleBackColor = False
        '
        'Button8
        '
        Me.Button8.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.Button8.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Button8.Font = New System.Drawing.Font("Arial", 6.75!)
        Me.Button8.ForeColor = System.Drawing.Color.Blue
        Me.Button8.Name = "Button8"
        Me.Button8.Text = "Trade It"
        Me.Button8.TextAlign = System.Drawing.ContentAlignment.TopCenter
        Me.Button8.UseVisualStyleBackColor = False
        '
        'Button9
        '
        Me.Button9.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.Button9.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Button9.Font = New System.Drawing.Font("Arial", 6.75!)
        Me.Button9.ForeColor = System.Drawing.Color.Blue
        Me.Button9.Name = "Button9"
        Me.Button9.Text = "Trade It"
        Me.Button9.TextAlign = System.Drawing.ContentAlignment.TopCenter
        Me.Button9.UseVisualStyleBackColor = False
        '
        'Button10
        '
        Me.Button10.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.Button10.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Button10.Font = New System.Drawing.Font("Arial", 6.75!)
        Me.Button10.ForeColor = System.Drawing.Color.Blue
        Me.Button10.Name = "Button10"
        Me.Button10.Text = "Trade It"
        Me.Button10.TextAlign = System.Drawing.ContentAlignment.TopCenter
        Me.Button10.UseVisualStyleBackColor = False
        '
        'Button11
        '
        Me.Button11.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.Button11.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Button11.Font = New System.Drawing.Font("Arial", 6.75!)
        Me.Button11.ForeColor = System.Drawing.Color.Blue
        Me.Button11.Name = "Button11"
        Me.Button11.Text = "Trade It"
        Me.Button11.TextAlign = System.Drawing.ContentAlignment.TopCenter
        Me.Button11.UseVisualStyleBackColor = False
        '
        'UnderlierRange
        '
        Me.UnderlierRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'VolatilityRange
        '
        Me.VolatilityRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'PortfolioDeltaRange
        '
        Me.PortfolioDeltaRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'RecommendationRange
        '
        Me.RecommendationRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'SymbolRange
        '
        Me.SymbolRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'QtyRange
        '
        Me.QtyRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'Sheet1
        '
        Me.StockTTypeCBox.BindingContext = Me.BindingContext
        Me.TickerCBox.BindingContext = Me.BindingContext
        Me.StockQtyTBox.BindingContext = Me.BindingContext
        Me.StockTradePreviewBtn.BindingContext = Me.BindingContext
        Me.StockTradeBtn.BindingContext = Me.BindingContext
        Me.OptionTTypeCBox.BindingContext = Me.BindingContext
        Me.SymbolCBox.BindingContext = Me.BindingContext
        Me.OptionQtyTBox.BindingContext = Me.BindingContext
        Me.OptionTradePreviewBtn.BindingContext = Me.BindingContext
        Me.OptionTradeBtn.BindingContext = Me.BindingContext
        Me.TradeItBtn.BindingContext = Me.BindingContext
        Me.Button1.BindingContext = Me.BindingContext
        Me.Button2.BindingContext = Me.BindingContext
        Me.Button3.BindingContext = Me.BindingContext
        Me.Button4.BindingContext = Me.BindingContext
        Me.Button5.BindingContext = Me.BindingContext
        Me.Button6.BindingContext = Me.BindingContext
        Me.Button7.BindingContext = Me.BindingContext
        Me.Button8.BindingContext = Me.BindingContext
        Me.Button9.BindingContext = Me.BindingContext
        Me.Button10.BindingContext = Me.BindingContext
        Me.Button11.BindingContext = Me.BindingContext
    End Sub

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Function NeedsFill(ByVal MemberName As String) As Boolean
        Return Me.DataHost.NeedsFill(Me, MemberName)
    End Function

    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
    Protected Overrides Sub OnShutdown()
        Me.QtyRange.Dispose()
        Me.SymbolRange.Dispose()
        Me.RecommendationRange.Dispose()
        Me.PortfolioDeltaRange.Dispose()
        Me.VolatilityRange.Dispose()
        Me.UnderlierRange.Dispose()
        Me.SecondsLeftCell.Dispose()
        Me.SecondsLeftCell1.Dispose()
        Me.Chart_1.Dispose()
        Me.Margin_ATCell.Dispose()
        Me.TPVCell.Dispose()
        Me.TECell.Dispose()
        Me.TE__weightedCell.Dispose()
        Me.TaTPVCell.Dispose()
        Me.TPV_at_StartCell.Dispose()
        Me.MaxMarginsCell.Dispose()
        Me._30MarginsCell.Dispose()
        Me.MarginsCell.Dispose()
        Me.cAcctCell.Dispose()
        Me.cAcctATCell.Dispose()
        Me.TransactionDateCell.Dispose()
        Me.CurrentDateCell.Dispose()
        Me.TransactionQueueLst.Dispose()
        Me.TeamIDCell.Dispose()
        Me.InterestSLTCell.Dispose()
        Me.TotalTValueCell.Dispose()
        Me.TotalTCostCell.Dispose()
        Me.PriceCell.Dispose()
        Me.QtyCell.Dispose()
        Me.SymbolCell.Dispose()
        Me.TypeCell.Dispose()
        Me.DateCell.Dispose()
        MyBase.OnShutdown()
    End Sub
End Class

Partial Friend NotInheritable Class Globals

    Private Shared _Sheet1 As Sheet1

    Friend Shared Property Sheet1() As Sheet1
        Get
            Return _Sheet1
        End Get
        Set(value As Sheet1)
            If (_Sheet1 Is Nothing) Then
                _Sheet1 = value
            Else
                Throw New System.NotSupportedException()
            End If
        End Set
    End Property
End Class
